//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyCompany("Trezorix")]
[assembly: AssemblyCopyright("Trezorix")]
[assembly: AssemblyProduct("Trezorix SparqlQueryApi")]
// the build version and revision number are set to the maximum possible value. The build server will set the appropriate values during build.
// intentionally: a deployed system will always have a lower version then any dev. compiled version.
[assembly: AssemblyVersion("0.1.65534.65534")]
[assembly: AssemblyInformationalVersion("0.1")]


